/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const InputsLazyImport = createFileRoute('/inputs')()
const FiltersLazyImport = createFileRoute('/filters')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const InputsLazyRoute = InputsLazyImport.update({
  path: '/inputs',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/inputs.lazy').then((d) => d.Route))

const FiltersLazyRoute = FiltersLazyImport.update({
  path: '/filters',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/filters.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/filters': {
      id: '/filters'
      path: '/filters'
      fullPath: '/filters'
      preLoaderRoute: typeof FiltersLazyImport
      parentRoute: typeof rootRoute
    }
    '/inputs': {
      id: '/inputs'
      path: '/inputs'
      fullPath: '/inputs'
      preLoaderRoute: typeof InputsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/filters': typeof FiltersLazyRoute
  '/inputs': typeof InputsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/filters': typeof FiltersLazyRoute
  '/inputs': typeof InputsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/filters': typeof FiltersLazyRoute
  '/inputs': typeof InputsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/filters' | '/inputs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/filters' | '/inputs'
  id: '__root__' | '/' | '/filters' | '/inputs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FiltersLazyRoute: typeof FiltersLazyRoute
  InputsLazyRoute: typeof InputsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FiltersLazyRoute: FiltersLazyRoute,
  InputsLazyRoute: InputsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/filters",
        "/inputs"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/filters": {
      "filePath": "filters.lazy.tsx"
    },
    "/inputs": {
      "filePath": "inputs.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
